### ISSUE TITLE
Warnings and errors recently appearing.

### ISSUE THREAD

**Issue by UgisL** [jsuar/Trello-Card-Title-Line-Breaks#1]
Hi,

I have recently noticed that the extension generates the following warning:
"Optional permission 'tabs' is redundant with the required permissions;this permission will be omitted."
Also, it generates a lot of these errors:
"Uncaught TypeError: Cannot read property 'indexOf' of undefined"

In addition, it does not seem to work anymore on my trello board. Any way to fix this?

**Comment by jsuar** [comment]
I made some recent changes to fix some issues, but I'm not able to reproduce what you're seeing. I'd recommend reinstalling the extension if possible. Also, let me know what version of Chrome you are running. Recommend upgrading that as well.

**Comment by UgisL** [comment]
Thanks a lot for responding and your work on this script system! I finally got to trying to improve the behaviour, I upgraded to:
Chrome Version 79.0.3945.117 (Official Build) (64-bit)

Downloaded fresh copy of your github repository and tried to drag crx file to the extension file as recommended, but something now is completely broken. I can not install extension and get message:
Package is invalid. Details: 'The "background.scripts" key cannot be used with manifest_version 3. Use the "background.service_worker" key instead.'

**Comment by jsuar** [comment]
@UgisL Sorry about that. I forgot to push up the manifest updates. Please try again using the steps in the readme: https://github.com/jsuar/Trello-Card-Title-Line-Breaks#how-to-install

It looks like CRX files aren't used anymore for unpublished extensions. I'll try to officially publish it this weekend also.

**Comment by UgisL** [comment]
Perfect! Now it works.
